version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: scheduler
    volumes:
      - mysql-data:/var/lib/mysql
      - ./backend/src/main/resources/db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.9-management
    ports:
      - "5672:5672"
      - "15672:15672"

  zookeeper:
    image: zookeeper:3.7
    ports:
      - "2181:2181"

  minio:
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: server /data
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - mysql
      - redis
      - rabbitmq
      - zookeeper
      - minio
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mysql-data:
  minio-data:
