spring:
  datasource:
    url: jdbc:mysql://localhost:3306/scheduler?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    
  redis:
    host: localhost
    port: 6379
    
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

zookeeper:
  connect-string: localhost:2181

minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin

logging:
  level:
    com.scheduler: DEBUG
